---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.7

suites:
  - name: default
    provisioner:
      policyfile: Policyfile.rb
    attributes:
      color: blue

verifier:
  name: inspec
